Add amsynth to the "high priority" section
pop-os/system76-scheduler pull request #31
Opened 2022-04-30 04:15 UTC by Slackadays

amsynth is a popular FOSS MIDI softsynth. To the scheduler, it doesn't look like an important task. Because of that, the scheduler currently gives it a nice value of 5. However, that spells trouble for audio applications because a higher priority task can steal CPU time and create pops or breaks in the synth output. Therefore, amsynth (and maybe other similar pro audio programs, too) should be treated as "high priority."

2022-05-02 19:04 UTC, n3m0-22 requested changes
While this does give amsynth high priority it only stays that way while in focus. As soon as another app is selected it drops back to low. This is an example of this happening recording amsynth with audacity

https://user-images.githubusercontent.com/11048214/166308970-cb819613-ca2f-487c-b37a-b5f9be0ab606.mp4

.

2022-05-02 20:13 UTC, Slackadays commented
Does system76-scheduler even have a mechanism to give certain programs a high priority regardless of focus? That'd be useful for the kinds of things like amsynth that may or may not be in the foreground but can't afford losing priority. Windows already has this problem with Intel Alder Lake and the closest thing to a solution there is to manually select some option for the program in question.

2022-05-02 21:18 UTC, 13r0ck commented
@n3m0-22
system76-scheduler is designed to prioritize when apps are in focus, and de-prioritize when focus is lost. That behavior is intentional. https://github.com/pop-os/system76-scheduler/blame/master/README.md#L3

@Slackadays 
Does this PR fix the issue with amsynth, or does proper functionality require the synth app to have high priority even when focus is lost?

2022-05-02 21:23 UTC, mmstick commented
Sounds like a bug. The scheduler service should retain priority for things that have a priority manually defined.

2022-05-04 16:09 UTC, mmstick commented
Superseded by #32

2022-05-04 16:09 UTC, closed without merging