Add support for dpkg-buildflags to build process
pop-os/system76-scheduler pull request #44
Opened 2022-05-20 01:05 UTC by techsy730

dpkg-buildflags is the Debian standard way of managing buildflags.

While things like `CFLAGS` probably won't have much relevance here, specifying `RUSTFLAGS` in `/etc/dpkg/buildflags.conf` still works just fine, despite dpkg-buildflags saying otherwise.

2022-05-20 01:08 UTC, techsy730 commented
This may sound a bit scary, but then again, this will only happen if the user downloads the source and trys to build it themselves. In which case, well, they already can do whatever they want.
And just leave the defaults (only `--release` it seems) for official builds

You can also clear out known incompatible build flags by exporting `DEB_RUSTFLAGS_MAINT_STRIP` in debian/rules, which will remove them regardless of what the user gives.

2022-05-20 15:02 UTC, mmstick approved these changes

2022-05-20 15:02 UTC, mmstick commented
What's the use case for this?

2022-05-20 21:07 UTC, jacobgkau requested changes
Attempting to build this locally gives an error message:

```
system76@pop-os:~/system76-scheduler$ dpkg-buildpackage -b -uc -us
dpkg-buildpackage: info: source package system76-scheduler
dpkg-buildpackage: info: source version 1.2.0
dpkg-buildpackage: info: source distribution jammy
dpkg-buildpackage: info: source changed by Michael Aaron Murphy <mmstick@gaze15.lan>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build .
 fakeroot debian/rules clean
debian/rules:15: *** missing separator.  Stop.
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
```

2022-05-30 18:17 UTC, techsy730 commented
> What's the use case for this?

Mostly for doing it the "debian" way of configuring stuff. Specifically if the builder wanted to configure the flags given to `rustc`.

But since it isn't technically supported by `dpkg-buildflags` for `RUSTFLAGS` (even though it works just fine)
I'm fine with just closing this PR (besides, there is a cleaner way to do this anyways).

If I can find a cleaner way, I'll send another PR.

2022-05-30 18:17 UTC, techsy730 commented
Closing

2022-05-30 18:17 UTC, closed without merging