failure to spawn execsnoop or PW watcher is a cause for panic
pop-os/system76-scheduler pull request #90
Opened 2023-04-28 13:34 UTC by cmm

2023-04-28 13:39 UTC, mmstick requested changes
The software shouldn't ever panic. That will cause systemd to be repeatedly restart it indefinitely.

2023-04-28 14:07 UTC, cmm commented
I think systemd gives up at some point?  Maybe not for dbus services, no idea.

I'll change the panics to errors then.

2023-04-28 14:35 UTC, mmstick approved these changes

2023-04-30 11:08 UTC, mmstick commented
I'll be merging your PRs into the `scheduler` branch so that they can be reviewed and QA in one pass.

2023-04-30 11:09 UTC, merged